"""
Highly divisible triangular number
Problem 12
"""


"""
QUESTIONS / SOLUTIONS
"""

# the sequence of triangle nubmers is generated by adding the natural numbers
# 7th triangle number would be:
# 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28

# the first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# list of first seven triangle numbers:
#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28

# 28 i sthe first triangle number to have over five divisors
# what is the value of the first triangle number to have over five hundred divisors
